### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by MikeBrWade** [dankrause/kcard-buildroot#18]
Dan you can delete this, but I and several of my coworkers are wanting to pick up this wifisd dev and we have several questions for you. We are all embedded software engineers by trade so we have a good basis of understanding in general but we were hoping to lean on some of your lessons learned and gotchas you have found.  I have rebuilt your rootfs and dmitry's kernel and they all seem to work but we were wanting to expand on that.. possibly repartitiong the NOR for just ther kernel and a tiny initramfs that then pulls in the main rootfs from NAND and perhaps has a SWAP partition etc. 

If IRC is the best way to contact you or some other way please let me know! Also if you know the best way to ping dmitry (his main site has comments disabled) and moroboshi.

**Comment by dankrause** [comment]
I've never actually contacted dmitry myself, I just noticed his work on hackaday, and on this forum thread: https://forum.openwrt.org/viewtopic.php?id=45820

Easiest way to contact me is google hangouts: dan -at- dankrause -dot- net

I'm also on freenode as dkrause frequently during the work day. Probably not much this week though.
